# changes

signChanges= list(
  c("FOLWER","FLOWER"),
  c("BIGHT","BRIGHT"),
  c("SIGINING","SIGNING"),
  c("-THE DOOR","THE DOOR"),
  c("1-1의 그림에서 옷의 색깔. 쥐색",NA),
  c("2형에서",NA),
  c("3가지가 있어 맞지?",NA),
  c("3개가 아니라 2개 있어",NA),
  c("3번째중에서 1째로 하늘 하얀 같은 색",NA),
  c("ACTION(눈) WITH ANGERINE",NA),
  c("ARM",NA),
  c("ARM+WHITE",NA),
  c("BACK-HAIR","BLACK-HAIR"),
  c("BEFORE-ROAD","ROAD"),
  c("BLACK","BLACK"),
  c("BLACK-DARK","BLACK-dark"),
  c("BLACK(ISL)","BLACK"),
  c("BLACK(JSL)","BLACK"),
  c("BLACK1-3수형으로 BLACK1-4수동","BLACK"),
  c("BLACKBOARD","BLACK"),
  c("BLIND ROAD","ROAD-BLIND"),
  c("BLOOD","RED-BLOOD"),
  c("BOOGER","BOOGER"),
  c("BOOGER코딱지와 같은 어두운 색","BOOGER"),
  c("BRIGHT","BRIGHT"),
  c("BRIGHT1","BRIGHT"),
  c("BROWN","BROWN"),
  c("BROWN(ISL+NSL)","BROWN"),
  c("BROWN(JSL)","BROWN"),
  c("CARRIAGEWAY(자동차도로)","ROAD"),
  c("CHECK?",NA),
  c("CLOWN","CLOWN"),
  c("COLOR","COLOR"),
  c("COLUMN","COLUMN"),
  c("COMBINE","COMBINE"),
  c("CORRECT","CORRECT"),
  c("CUTTING(ACTION) ORANGE","ORANGE"),
  c("DARK","DARK"),
  c("DARK(VERY LITTLE)","DARK"),
  c("DARK1","DARK"),
  c("DARK1#LITTLE","DARK"),
  c(" DIFFERENT ","DIFFERENT"),
  c("DO NOT UNDERSTAND","DO NOT UNDERSTAND"),
  c("DOOR","DOOR"),
  c("DOOR-YESTERDAY-THE DOOR","THE DOOR"),
  c("DRINK","DRINK"),
  c("DRIVE","DRIVE"),
  c("EAT","EAT"),
  c("EAT WITH BOX","EAT+BOX"),
  c("EAT^PEEL","EAT+PEEL"),
  c("FACE","FACE"),
  c("FACE#DARK","FACE+DARK"),
  c("FLOOR","FLOOR"),
  c("FLOWER","FLOWER"),
  c("FLOWER+NOT","FLOWER"),
  c("FLOWER+WHAT^SIGN?","FLOWER"),
  c("GOOD","GOOD"),
  c("GREEN","GREEN"),
  c("GREEN-CHEST","GREEN-CHEST"),
  c("GREEN-CHEST\t","GREEN-CHEST"),
  c("GREEN-NSL","GREEN-NSL"),
  c("GREEN-NSL\t","GREEN-NSL"),
  c("GREEN(ISL)","GREEN-CHEST"),
  c("GREEN(NSL)","GREEN-NSL"),
  c("GREEN1(ISL)","GREEN-CHEST"),
  c("GREEN2",NA),
  c("GREEN2(NSL)",NA),
  c("I / ME","ME"),
  c("INDIA","RED-BROW"),
  c("IX","IX"),
  c("IX:TONGUE +IX:LIP+DIFFERENT","IX:TONGUE +IX:LIP+DIFFERENT"),
  c("IX:TONGUE+IX:LIP","IX:TONGUE+IX:LIP"),
  c("JORDAN","JORDAN"),
  c("L","L"),
  c("LEAF","LEAF"),
  c("LEMON","LEMON"),
  c("LIGHT","BRIGHT"),
  c("LIP","LIP"),
  c("LIPSTICK","LIPSTICK"),
  c("LITTER","LITTER"),
  c("LW:CAP(POLICE)'S LW:BOLD PATTRN OF DRESS","LW:CAP(POLICE)'S LW:BOLD PATTRN OF DRESS"),
  c("ME","ME"),
  c("MIX","MIX"),
  c("NIGHT+DARK","BRIGHT+DARK"),
  c("NO",NA),
  c("NO?",NA),
  c("NOSE-PENDANT","NOSE-PENDANT"),
  c("NOT","NOT"),
  c("OHTER","OTHER"),
  c("ORANGE","ORANGE"),
  c("ORANGE JUICE","ORANGE"),
  c("ORANGE PEEL","ORANGE"),
  c("ORANGE?","ORANGE"),
  c("OUT","OUT"),
  c("PAINT THE WALL","PAINT THE WALL"),
  c("PEEL","PEEL"),
  c("PEEL COLOR TWO","PEEL"),
  c("PEEL ORANGE EAT SEED  THROW-OUT(씨앗먹다가 버리다)","ORANGE"),
  c("PEEL ORANGE^냄새맡게 되는 특성","ORANGE"),
  c("PINK","PINK"),
  c("PLANTS","PLANTS"),
  c("POINTING(하늘)","IX-SKY"),
  c("PRAYER","PRAYER"),
  c("RED","RED"),
  c("RED + NOT+DIFFERENT","RED"),
  c("RED- BROW","RED-BROW"),
  c("RED-BLOOD","RED-BLOOD"),
  c("RED-BROW","RED-BROW"),
  c("RED(INSL+JSL)","RED"),
  c("RED(NSL)","RED-BROW"),
  c("REPEAT","REPEAT"),
  c("REPETITION","REPEAT"),
  c("RING","RING"),
  c("SAME","SAME"),
  c("SAME?","SAME"),
  c("SAME2","SAME"),
  c("SEA","SEA"),
  c("SIGN","SIGNING"),
  c("SIGNING","SIGNING"),
  c("SIWASH","SIWASH"),
  c("SKY","SKY"),
  c("SKY?","SKY"),
  c("SKY+SEA?","SKY"),
  c("SUN","SUN"),
  c("T0보다 CHECK쪽이 맞음?","REPEAT"),
  c("TABLE","TABLE"),
  c("THAT","THAT"),
  c("THAT IS ORANGE PEEL SAME","ORANGE"),
  c("THAT!","THAT"),
  c("THE DOOR","THE DOOR"),
  c("THERE","THERE"),
  c("TONGUE","TONGUE"),
  c("TONGUE+DIFFFERENT","TONGUE"),
  c("TREE","TREE"),
  c("TREE DARK","TREE"),
  c("TREE-GREEN2/1","TREE"),
  c("TREE-POST","TREE-POST"),
  c("UNDERSTAND","UNDERSTAND"),
  c("WALL","WALL"),
  c("WATCH","WATCH"),
  c("WATER","WATER"),
  c("WHITE","WHITE"),
  c("YELLOW","YELLOW"),
  c("YELLOW-CHEST","YELLOW-CHEST"),
  c("YELLOW-CHEST+BRIGHT","YELLOW-CHEST"),
  c("YELLOW-CHIN","YELLOW-CHIN"),
  c("YELLOW-NOSE","YELLOW-NOSE"),
  c("YELLOW(JSL)","YELLOW-CHIN"),
  c("YELLOW(NSL)","YELLOW-CHEST"),
  c("YES","YES"),
  c("YES!","YES"),
  c("YOU","YOU"),
  c("그럼 첫째 딱맞은 것 2째 약간 어둡게 그치? 그거야!",NA),
  c("두번째 약간 어둡게",NA),
  c("두번째로 어두운 것?",NA),
  c("두번째야!",NA),
  c("벽","WALL"),
  c("세번째는 팔과 같아",NA),
  c("세번째야",NA),
  c("수화 같은가?",NA),
  c("아까 말했듯이 오렌지색!","ORANGE"),
  c("첫번째 밝은 것 두번째 어두운 것인데 두번째야!",NA),
  c("첫번째는 ACTION(눈으로 귤을 말하면서 밝고)",NA),
  c("첫째는 밝은 것",NA),
  c("첫째로 하늘 둘째 바다 셋째 어두운 것으로 셋째?",NA),
  c("하늘과 같은데.. 바다보다 더 밝은데 그건 하얀색을 더해서 나온 색",NA),
  c("하얀색이라고 하지말아. 그냥 하늘색이지?","NO")
)